from enum import Enum

class InputColumn(Enum):
  NO = 'no'
  KDDEPT = 'kddept'
  NMDEPT = 'nmdept'
  KDDEKON = 'kddekon'
  NMDEKON = 'nmdekon'
  KDKABKOTA = 'kdkabkota'
  NMKABKOTA = 'nmkabkota'
  KDKANWIL = 'kdkanwil'
  KDKPPN = 'kdkppn'
  NMKPPN = 'nmkppn'
  KDSATKER = 'kdsatker'
  NMSATKER = 'nmsatker'
  KDFUNGSI = 'kdfungsi'
  NMFUNGSI = 'nmfungsi'
  KDPROGRAM = 'kdprogram'
  NMPROGRAM = 'nmprogram'
  KDGIAT = 'kdgiat'
  NMGIAT = 'nmgiat'
  KDOUTPUT = 'kdoutput'
  NMOUTPUT = 'nmoutput'
  KDAKUN = 'kdakun'
  NMAKUN = 'nmakun'
  KDSDANA = 'kdsdana'
  NMSDANA = 'nmsdana'
  KAT_OUT = 'kat_out'
  URAIAN_KAT_OUT = 'uraian_kat_out'
  PAGU = 'pagu'
  REALISASI = 'realisasi'
  BLOKIR = 'blokir'
